import { useEffect,useState } from 'react';
import api from '../services/api.js';

export default function Admin(){
 const [products,setProducts]=useState([]); const [orders,setOrders]=useState([]); const [tab,setTab]=useState('products'); const [form,setForm]=useState({name:'',description:'',price:'',category:'Fashion',image:'',rating:4.5,stock:10,featured:false});
 async function load(){const [p,o]=await Promise.all([api.get('/products'),api.get('/orders')]);setProducts(p.data);setOrders(o.data)}
 useEffect(()=>{load()},[]);
 async function add(e){e.preventDefault();await api.post('/products',{...form,price:Number(form.price),stock:Number(form.stock),rating:Number(form.rating)});setForm({name:'',description:'',price:'',category:'Fashion',image:'',rating:4.5,stock:10,featured:false});load()}
 async function remove(id){if(confirm('Delete this product?')){await api.delete(`/products/${id}`);load()}}
 async function status(id,status){await api.put(`/orders/${id}/status`,{status});load()}
 return <main className="container page"><div className="page-title"><span className="eyebrow">ADMIN</span><h1>Store dashboard</h1><p>Manage products and customer orders.</p></div><div className="admin-tabs"><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}>Products ({products.length})</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Orders ({orders.length})</button></div>{tab==='products'?<div className="admin-grid"><form className="panel admin-form" onSubmit={add}><h2>Add product</h2><input required placeholder="Product name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><textarea required placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input required type="number" placeholder="Price" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Fashion</option><option>Electronics</option><option>Shoes</option><option>Home</option></select><input required placeholder="Image URL" value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/><input type="number" min="0" placeholder="Stock" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><button className="btn btn-primary">Add product</button></form><div className="admin-list">{products.map(p=><div className="admin-row" key={p._id}><img src={p.image}/><div><b>{p.name}</b><span>₦{p.price.toLocaleString()} • {p.stock} stock</span></div><button className="remove" onClick={()=>remove(p._id)}>Delete</button></div>)}</div></div>:<div className="admin-list">{orders.map(o=><div className="admin-order" key={o._id}><div><b>#{o._id.slice(-8).toUpperCase()}</b><span>{o.user?.name} • ₦{o.total.toLocaleString()}</span></div><select value={o.status} onChange={e=>status(o._id,e.target.value)}><option>Processing</option><option>Shipped</option><option>Delivered</option><option>Cancelled</option></select></div>)}</div>}</main>
}
